### ISSUE TITLE
minecraft:ore_ancient_debris_small typed incorrectly as minecraft:ore_debris_small in worldgen/biome/basalt_deltas.json

### ISSUE THREAD

**Issue by calebwestdev** [slicedlime/examples#18]
minecraft:ore_ancient_debris_small is typed incorrectly as minecraft:ore_debris_small in worldgen/biome/basalt_deltas.json

On line 63, I noticed it was mistyped because no such feature "minecraft:ore_debris_small.json" exists in worldgen/configured_feature, only "minecraft:ore_ancient_debris_small"

**Comment by oskarkk** [comment]
The features referenced in biomes are not configured features, they're placed features. And in placed_features there's `ore_debris_small` and `ore_ancient_debris_large`. Inconsistent naming, but no errors.

**Comment by calebwestdev** [comment]
Ah ok, gotcha, I still kinda new to this stuff but learning as I go
