### ISSUE TITLE
Using this example in a datapack always gives the same biome map (No random seed?)

### ISSUE THREAD

**Issue by NBSgamesAT** [slicedlime/examples#8]
Just putting the provided dimension, dimension_type and worldgen folders into a datapack under data\minecraft always generates a similar looking map with an ocean biome, an mountain biome, a dark_forest biome and a badlands biome near the spawn area.

I suspect that the seeds defined in dimension\overworld.json, dimension\the_nether.json, dimension\the_end.json are messing with the actual world generation. Is there a way to define that a random seed should be taking or is the standard value 0 supposed to do just that, but for some reason doesn't.

I've included the my datapack [here](https://github.com/slicedlime/examples/files/6790755/testdata_pack.zip). The provided files are from commit 7c54f55409f395a0aa517729669b20d570969f30.

**Comment by misode** [comment]
This is not the place to report bugs with the game, for that go to the [bug tracker](https://bugs.mojang.com). The bugs you mention are [MC-195717](https://bugs.mojang.com/browse/MC-195717) and [MC-187262](https://bugs.mojang.com/browse/MC-187262).

**Comment by NBSgamesAT** [comment]
I was trying to find the bugs in the bug tracker, looks like I wasn't search properly. Thank you for sending making me aware of 'em because I started to think that the provided files just didn't work

**Comment by NBSgamesAT** [comment]
> This is not the place to report bugs with the game, for that go to the [bug tracker](https://bugs.mojang.com). The bugs you mention are [MC-195717](https://bugs.mojang.com/browse/MC-195717) and [MC-187262](https://bugs.mojang.com/browse/MC-187262).

> I was trying to find the bugs in the bug tracker, looks like I wasn't search properly. Thank you for sending making me aware of 'em because I started to think that the provided files just didn't work

With all of that being said: I'm closing this issue. For everyone else: Please go to the bugs in the bug tracker and upvote both issues there...
